### ISSUE TITLE
cannot  find imageoptimal in file menu when build from source

### ISSUE THREAD

**Issue by buaaluwentao** [yeahdongcn/RSImageOptimPlugin#10]
when build from source after restarting Xcode,  I cannot  find imageoptimal option in file menu.I do not why, my Xcode is 10.1, and I can confirm the plugin was at the right location(I have RSImageOptimPlugin.xcplugin at ~/Library/Application Support/Developer/Shared/Xcode/Plug-ins).
any answer will be grateful.

**Comment by yeahdongcn** [comment]
Please note that plugins are not supported by Xcode 8. Please see: https://github.com/alcatraz/Alcatraz/issues/475
