### ISSUE TITLE
can't find menu

### ISSUE THREAD

**Issue by culmek** [yeahdongcn/RSImageOptimPlugin#7]
I can't install with Alcatraz and can't find menu in "File" when I build your project...

**Comment by readefries** [comment]
I had the same, and after I removed and reinstalled Alcatraz, it worked like a charm!

**Comment by yeahdongcn** [comment]
https://github.com/yeahdongcn/RSImageOptimPlugin/commit/a66c166e65616064569eea19952f7bf6a711197f
