### ISSUE TITLE
ImageOptim not showing at xCode 7.3.1

### ISSUE THREAD

**Issue by RafaelPlantard** [yeahdongcn/RSImageOptimPlugin#9]
I install the plugin with Package Manager on xCode but not works..
Can you helps me?

<img width="1280" alt="screen shot 2016-05-24 at 17 02 25" src="https://cloud.githubusercontent.com/assets/5968478/15518059/6151c156-21d1-11e6-8954-39a675b74c33.png">

**Comment by yeahdongcn** [comment]
Fixed.

**Comment by RafaelPlantard** [comment]
Thanks I will try...
